---
title: "movement"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggpubr)
library(png)
library(gganimate)
theme_set(theme_bw())
```

```{r}
movement_fri <- read_csv("park-movement-Fri.csv")
```


```{r}
movement_sat <- read_csv("park-movement-Sat.csv")
```

```{r}
movement_sun <- read_csv("park-movement-Sun.csv")
```

```{r}
img <- readPNG("map2.png")
```


```{r}
ggplot(movement_sun, aes(x = X, y = Y))+
  background_image(img)+
  geom_point()
```


```{r}
new_sun <- movement_sun %>% 
  filter(id == "378256" | id == "1159870" | id == "1784014" )
```

```{r}
p <- ggplot(data = new_sun, aes(x = X, y = Y, color = factor(id)))+
  geom_point()
p
```

```{r}
p + 
  transition_components(time = time(Timestamp))+
  labs(title = "Time: {frame_time}")
  
```

```{r}
library(plotly)

my_p <- new_sun %>%
  plot_ly(
    x = ~X,
    y = ~Y,
    color = ~id,
    frame = ~time(Timestamp),
    type
  )
```

